export const Partidos = [
  { partido: "Todos" },
  { partido: "PT" },
  { partido: "PSDB" },
  { partido: "PSOL" },
  { partido: "PSL" },
  { partido: "PSB" },
  { partido: "PDT" },
  { partido: "PCdoB" },
  { partido: "MDB" },
  { partido: "DEM" },
  { partido: "Cidadania" },
  { partido: "Avante" },
  { partido: "PP" },
  { partido: "PSC" },
  { partido: "PL" },
  { partido: "PRTB" },
  { partido: "PATRI" },
  { partido: "PROS" },
  { partido: "PODE" },
  { partido: "PTB" },
  { partido: "PTC" },
]